services:
  - type: web
    name: online-library-backend
    env: python
    pythonVersion: "3.12.9"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn simpleAuthentication.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: simpleAuthentication.settings
      - key: PYTHONUNBUFFERED
        value: 1
